# Eliminação gaussiana sem pivoteamento

Antes dessa aula você deve assistir aos vídeos abaixo.

1. [Matrizes com python](https://youtu.be/FgXrDIAlwpk)
1. [Eliminação gaussiana](https://youtu.be/FKPrlNHqwT0)

In [1]:
import numpy as np
import pandas as pd # utilizado apenas na impressão de algumas matrizes

1. **Inicialize uma matriz A de dimensão $3\times 3$ e uma matriz $b$ de dimensão $3 \times 1$ com números aleatórios.**

In [64]:
np.random.seed(2)
A = np.random.rand(3, 3)
b = np.random.rand(3, 1)
print(A)
print('')
print(b)

[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]]

[[0.26682728]
 [0.62113383]
 [0.52914209]]

Vamos utilizar a eliminação gaussiana para determinar $x$, de modo que $Ax = b$. O python será utilizado como uma calculadora. Para preserver as matrizes `A` e `b` vamos cópias `copia_A` e `copia_b`.

In [66]:
copia_A = np.copy(A)
copia_b = np.copy(b)
print(copia_A)
print('')
print(copia_b)

[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]]

[[0.26682728]
 [0.62113383]
 [0.52914209]]

**2. Qual o valor do primeiro multiplicador? Não utilize os números e sim referências a matriz.**

In [67]:
pivo = A[0, 0]
m = -A[1, 0] / pivo
print(pivo)
print(m)

0.43599490214200376
-0.9984575289288409

Adicione $m \cdot linha0$ a $linha 1$.

In [68]:
A[1] = m * A[0] + A[1]
b[1] = m * b[0] + b[1]

In [69]:
# Se sua resposta estiver certa A[1,0] será = 0
A

array([[ 0.4359949 ,  0.02592623,  0.54966248],
       [ 0.        ,  0.39448156, -0.21847982],
       [ 0.20464863,  0.61927097,  0.29965467]])

**3. Determine o próximo multiplicador? E atualize a linha 2 da matriz A.**

In [70]:
m = -A[2, 0] / pivo
A[2] = m * A[0] + A[2]
b[2] = m * b[0] + b[2]

In [71]:
# Sua resposta está correta? 
print(A)

[[ 0.4359949   0.02592623  0.54966248]
 [ 0.          0.39448156 -0.21847982]
 [ 0.          0.60710163  0.0416524 ]]

**4. O trabalho com a primeira coluna está finalizado. Determine o próximo pivô.**

In [72]:
pivo = A[1, 1]
pivo

0.3944815607221764

**5. Determine o próximo multiplicador e atualize a linha 2.**

In [73]:
m = -A[2, 1] / pivo
A[2] = m * A[1] + A[2]
b[2] = m * b[1] + b[2]

In [74]:
print('A= \n', A)
print()
print('b= \n', b)

A=
 [[ 0.4359949   0.02592623  0.54966248]
 [ 0.          0.39448156 -0.21847982]
 [ 0.          0.          0.3778898 ]]

b=
 [[ 0.26682728]
 [ 0.35471813]
 [-0.14200838]]

Agora a matriz A está em um formato triangular superior e precisamos determinar os valores de `x[0]`, `x[1]` e `x[2]`.

In [79]:
x = np.zeros(3)
x

array([0., 0., 0.])

**6. Determine o valor de `x[2]`.**

In [80]:
x[2] = b[2] / A[2, 2]
print(x[2])

-0.3757931081936095

**7. Determine o valor de `x[1]`.**

In [81]:
x[1] = (b[1] - A[1, 2]*x[2]) / A[1, 1]
print(x[1])

0.6910713912322132

**8. Determine o valor de x[0].**

In [82]:
x[0] = (b[0] - A[0, 1]*x[1] - A[0, 2]* x[2]) / A[0, 0]
print(x[0])

1.0446676481443158

Verificando o resultado

In [83]:
copia_A @ x

array([0.26682728, 0.62113383, 0.52914209])

In [84]:
copia_b

array([[0.26682728],
       [0.62113383],
       [0.52914209]])

**9. Combine o código que você escreveu até agora para resolver sistemas lineares com 3 equações e 3 incógnitas.**

In [87]:
def eliminacao_gaussiana_3(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes é uma matriz 3 por 3
    termos_independentes é uma matriz 3 por 1
    Não será necessário realizar pivoteamento, se o pivo for igual a zero ocorrerá um erro (divisão por zero)
    '''
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    
    # seu código aqui
    pivo = A[0, 0]
    
    m = -A[1, 0] / pivo
    A[1] = m * A[0] + A[1]
    b[1] = m * b[0] + b[1]
    
    m = -A[2, 0] / pivo
    A[2] = m * A[0] + A[2]
    b[2] = m * b[0] + b[2]
    
    pivo = A[1, 1]
    
    m = -A[2, 1] / pivo
    A[2] = m * A[1] + A[2]
    b[2] = m * b[1] + b[2]
    

    x = np.zeros(3)
    x[2] = b[2] / A[2, 2]
    x[1] = (b[1] - A[1, 2]*x[2]) / A[1, 1]
    x[0] = (b[0] - A[0, 1]*x[1] - A[0, 2]* x[2]) / A[0, 0]
    
    return x

In [88]:
A1 = np.random.rand(3, 3)
b1 = np.random.rand(3, 1)

In [89]:
x = eliminacao_gaussiana_3(A1, b1)

In [91]:
y = A1 @ x
print('b1 = ', b1)
print('y  = ', y)

b1 =  [[0.0652865 ]
 [0.42812233]
 [0.09653092]]
y  =  [0.0652865  0.42812233 0.09653092]

Agora vamos inicializar uma matriz A com dimensão $5 \times 5$ e uma matriz $b$ com dimensão $5 \times 1$.

In [93]:
A = np.random.rand(5, 5)
b = np.random.rand(5, 1)

In [94]:
print(A)

[[0.40627504 0.02720237 0.24717724 0.06714437 0.99385201]
 [0.97058031 0.80025835 0.60181712 0.76495986 0.16922545]
 [0.29302323 0.52406688 0.35662428 0.04567897 0.98315345]
 [0.44135492 0.50400044 0.32354132 0.25974475 0.38688989]
 [0.8320169  0.73674706 0.37921057 0.01301734 0.79740494]]

**10. Realize operações sobre linhas para zerar os valores abaixo do pivô.**

In [95]:
pivo = A[0, 0]

m = -A[1, 0] / pivo
A[1] = m * A[0] + A[1]
b[1] = m * b[0] + b[1]

m = -A[2, 0] / pivo
A[2] = m * A[0] + A[2]
b[2] = m * b[0] + b[2]

m = -A[3, 0] / pivo
A[3] = m * A[0] + A[3]
b[3] = m * b[0] + b[3]

m = -A[4, 0] / pivo
A[4] = m * A[0] + A[4]
b[4] = m * b[0] + b[4]

In [96]:
pd.DataFrame(A)

              0         1         2         3         4
0  4.062750e-01  0.027202  0.247177  0.067144  0.993852
1  1.110223e-16  0.735273  0.011317  0.604554 -2.205061
2  0.000000e+00  0.504447  0.178349 -0.002748  0.266344
3  0.000000e+00  0.474449  0.055022  0.186803 -0.692776
4  0.000000e+00  0.681039 -0.126987 -0.124489 -1.237920

Agora vamos inicializar uma matriz A com dimensão $10 \times 10$ e uma matriz $b$ com dimensão $10 \times 1$.

In [97]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)

pd.DataFrame(A)

          0         1         2  ...         7         8         9
0  0.497074  0.414906  0.350872  ...  0.041798  0.738400  0.657512
1  0.214636  0.416753  0.643842  ...  0.133954  0.868917  0.748778
2  0.798586  0.543345  0.220838  ...  0.913915  0.419735  0.540192
3  0.608442  0.826250  0.623563  ...  0.699521  0.245811  0.186627
4  0.110583  0.274059  0.010250  ...  0.283756  0.214924  0.285604
5  0.471410  0.549497  0.845113  ...  0.161467  0.870146  0.217402
6  0.741755  0.653021  0.798886  ...  0.030589  0.357135  0.589782
7  0.052223  0.065664  0.043501  ...  0.432389  0.619641  0.290427
8  0.615255  0.953660  0.448015  ...  0.525733  0.042429  0.164419
9  0.450227  0.707971  0.777588  ...  0.481458  0.748374  0.857840

[10 rows x 10 columns]

**11. Escreva um código para zerar os elementos abaixo do pivô da coluna 0**

In [98]:
pivo = A[0, 0]

for k in range(1, 10):
    m = -A[k, 0] / pivo
    A[k] = m * A[0] + A[k]
    b[k] = m * b[0] + b[k]

pd.DataFrame(A)

          0         1         2  ...         7         8         9
0  0.497074  0.414906  0.350872  ...  0.041798  0.738400  0.657512
1  0.000000  0.237598  0.492336  ...  0.115906  0.550077  0.464865
2  0.000000 -0.123232 -0.342864  ...  0.846764 -0.766558 -0.516151
3  0.000000  0.318385  0.194079  ...  0.648358 -0.658026 -0.618200
4  0.000000  0.181756 -0.067808  ...  0.274457  0.050654  0.139328
5  0.000000  0.156013  0.512357  ...  0.121827  0.169870 -0.406163
6  0.000000  0.033880  0.275299  ... -0.031783 -0.744737 -0.391386
7  0.000000  0.022074  0.006638  ...  0.427998  0.542065  0.221348
8  0.000000  0.440109  0.013722  ...  0.473998 -0.871527 -0.649419
9  0.000000  0.332168  0.459784  ...  0.443600  0.079565  0.262294

[10 rows x 10 columns]

**12. Escreva um código para zerar os elementos abaixo do pivô da coluna 1**

In [99]:
pivo = A[1, 1]

for k in range(2, 10):
    m = -A[k, 1] / pivo
    A[k] = m * A[1] + A[k]
    b[k] = m * b[1] + b[k]
    
pd.DataFrame(A)

          0             1         2  ...         7         8         9
0  0.497074  4.149058e-01  0.350872  ...  0.041798  0.738400  0.657512
1  0.000000  2.375977e-01  0.492336  ...  0.115906  0.550077  0.464865
2  0.000000  1.387779e-17 -0.087510  ...  0.906880 -0.481257 -0.275045
3  0.000000  0.000000e+00 -0.465660  ...  0.493042 -1.395138 -1.241127
4  0.000000  0.000000e+00 -0.444432  ...  0.185792 -0.370140 -0.216281
5  0.000000  0.000000e+00  0.189077  ...  0.045720 -0.191324 -0.711405
6  0.000000  0.000000e+00  0.205095  ... -0.048310 -0.823175 -0.457674
7  0.000000  0.000000e+00 -0.039101  ...  0.417230  0.490961  0.178161
8  0.000000  0.000000e+00 -0.898246  ...  0.259302 -1.890450 -1.510502
9  0.000000  0.000000e+00 -0.228515  ...  0.281560 -0.689458 -0.387600

[10 rows x 10 columns]

**13. Escreva um código para zerar os elementos abaixo do pivô da coluna 2**

In [100]:
pivo = A[2, 2]

for k in range(3, 10):
    m = -A[k, 2] / pivo
    A[k] = m * A[2] + A[k]
    b[k] = m * b[2] + b[k]

pd.DataFrame(A)

          0             1             2  ...         7         8         9
0  0.497074  4.149058e-01  3.508719e-01  ...  0.041798  0.738400  0.657512
1  0.000000  2.375977e-01  4.923360e-01  ...  0.115906  0.550077  0.464865
2  0.000000  1.387779e-17 -8.751048e-02  ...  0.906880 -0.481257 -0.275045
3  0.000000 -7.384634e-17  0.000000e+00  ... -4.332637  1.165724  0.222442
4  0.000000 -7.047987e-17 -5.551115e-17  ... -4.419897  2.073979  1.180567
5  0.000000  2.998459e-17  0.000000e+00  ...  2.005140 -1.231137 -1.305672
6  0.000000  3.252485e-17  0.000000e+00  ...  2.077109 -1.951080 -1.102287
7  0.000000 -6.200803e-18  0.000000e+00  ...  0.012022  0.705994  0.301055
8  0.000000 -1.424477e-16  0.000000e+00  ... -9.049310  3.049387  1.312685
9  0.000000 -3.623892e-17 -2.775558e-17  ... -2.086566  0.567245  0.330624

[10 rows x 10 columns]

**14. Existe repetição nesses códigos. Agora escreva um laço para zerar os elementos abaixo do pivô da coluna 0 até a coluna 8.**

In [101]:
for j in range(0, 9):
    pivo = A[j, j]

    for k in range(j+1, 10):
        m = -A[k, j] / pivo
        A[k] = m * A[j] + A[k]
        b[k] = m * b[j] + b[k]
        A[k, j] = 0

pd.DataFrame(A)

          0         1         2  ...         7         8         9
0  0.497074  0.414906  0.350872  ...  0.041798  0.738400  0.657512
1  0.000000  0.237598  0.492336  ...  0.115906  0.550077  0.464865
2  0.000000  0.000000 -0.087510  ...  0.906880 -0.481257 -0.275045
3  0.000000  0.000000  0.000000  ... -4.332637  1.165724  0.222442
4  0.000000  0.000000  0.000000  ... -2.440005  1.541276  1.078918
5  0.000000  0.000000  0.000000  ... -0.337243 -0.230011 -0.785650
6  0.000000  0.000000  0.000000  ... -0.677669 -0.036464  0.310192
7  0.000000  0.000000  0.000000  ... -0.056291 -0.019359 -0.071910
8  0.000000  0.000000  0.000000  ...  0.000000  0.485508  1.313097
9  0.000000  0.000000  0.000000  ...  0.000000  0.000000 -0.061756

[10 rows x 10 columns]

**15. Escreva uma função que realize a primeira parte da eliminação gaussiana, convertendo a matriz em uma matriz triangular superior.**

In [103]:
def eliminacao_gaussiana(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes é uma matriz 3 por 3
    termos_independentes é uma matriz 3 por 1
    Não será necessário realizar pivoteamento, se o pivo for igual a zero ocorrerá um erro (divisão por zero)
    '''
    
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    tamanho = len(A)

    for j in range(0, tamanho-1):
        pivo = A[j, j]

        for k in range(j+1, tamanho):
            m = -A[k, j] / pivo
            A[k] = m * A[j] + A[k] # esta linha está realizando muitas operações desnecessárias
            b[k] = m * b[j] + b[k]
            A[k, j] = 0
    
    
    return A, b

In [114]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)

tA, tb = eliminacao_gaussiana(A, b)

pd.DataFrame(tA)

          0         1         2  ...         7          8          9
0  0.942421  0.371271  0.729001  ...  0.287635   0.967113   0.668099
1  0.000000  0.179840 -0.051728  ...  0.094029   0.426985   0.200269
2  0.000000  0.000000 -0.060800  ...  0.022483   0.043040   0.389598
3  0.000000  0.000000  0.000000  ... -0.131422  -1.653772   1.705249
4  0.000000  0.000000  0.000000  ... -0.317628  -3.198070   1.741894
5  0.000000  0.000000  0.000000  ... -0.672183  -7.952684   3.453823
6  0.000000  0.000000  0.000000  ...  3.297563  41.461702 -17.472904
7  0.000000  0.000000  0.000000  ... -0.185823  -7.659284   3.104579
8  0.000000  0.000000  0.000000  ...  0.000000 -20.319933   8.348225
9  0.000000  0.000000  0.000000  ...  0.000000   0.000000   0.833757

[10 rows x 10 columns]

**16. Agora precisamos determinar as soluções do sistema.**

In [115]:
x = np.zeros(10)

x[9] = tb[9] / tA[9, 9]
x[8] = (tb[8] - tA[8, 9] * x[9]) / tA[8, 8]
x[7] = (tb[7] - tA[7, 8] * x[8] - tA[7, 9] * x[9]) / tA[7, 7]
x[6] = (tb[6] - tA[6, 7] * x[7] - tA[6, 8] * x[8]- tA[6, 9] * x[9]) / tA[6, 6]

**17. Existe uma repetição no código acima, escreva um laço que calcule os valores de x[k] com k variando de 9 até 0.**

In [116]:
x[9] = tb[9] / tA[9, 9]

for k in range(8, -1, -1):
    soma = tb[k]
    for t in range(k, 10):
        soma = soma - tA[k, t] * x[t]

    x[k] = soma / tA[k, k]

In [117]:
x

array([ 6.05040107e+01,  6.77814093e+01, -5.34327743e+01, -3.40697567e+01,
       -4.16708604e+01,  9.77660929e+01, -9.53200873e+01, -9.54163404e+01,
        8.74194248e-17, -1.15306545e+00])

In [118]:
A @ x

array([  0.30075307,   0.51144873,   0.78622852,   0.81250558,
         0.53284089,   0.80633521,   8.63939655,  18.56603506,
       -43.56264801, -58.49491316])

In [119]:
b

array([[0.30075307],
       [0.51144873],
       [0.78622852],
       [0.81250558],
       [0.53284089],
       [0.80633521],
       [0.03427548],
       [0.15406612],
       [0.74818503],
       [0.3848699 ]])

**18. Escreva uma função que determine as soluções de um sistema com matriz de coeficientes triangular superior**

In [120]:
def triangular_superior(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes: matriz triangular superior
    termos_independentes: termos independentes do sistema retangular superior
    
    retorna a solução do sistema
    '''
    tamanho = len(matriz_coeficientes)
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    
    
    x = np.zeros(tamanho)
    x[tamanho-1] = b[tamanho-1] / A[tamanho-1, tamanho-1]

    for k in range(tamanho-2, -1, -1):
        soma = b[k]
        for t in range(k, tamanho):
            soma = soma - A[k, t] * x[t]

        x[k] = soma / A[k, k]
    
    return x

In [121]:

triangular_superior(tA, tb)

array([-0.17334705, -1.98796251,  1.60650773,  2.7480311 ,  2.02403853,
       -1.8479352 ,  3.65279065,  1.78629211, -2.31490592, -1.15306545])

In [122]:
A @ x

array([  0.30075307,   0.51144873,   0.78622852,   0.81250558,
         0.53284089,   0.80633521,   8.63939655,  18.56603506,
       -43.56264801, -58.49491316])

In [123]:
b

array([[0.30075307],
       [0.51144873],
       [0.78622852],
       [0.81250558],
       [0.53284089],
       [0.80633521],
       [0.03427548],
       [0.15406612],
       [0.74818503],
       [0.3848699 ]])

**19. Combine as funções `eliminação_gaussiana` e `triangular_superior` para resolver um sistema de equações Ax=b com $det(A) \neq 0$**

In [125]:
def resolver_sistema(matriz_coeficientes, termos_independentes):
    tA, tb = eliminacao_gaussiana(matriz_coeficientes, termos_independentes)
    x = triangular_superior(tA, tb)
    return x

In [127]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)

x = resolver_sistema(A, b)

In [128]:
A @ x

array([0.4426011 , 0.13941709, 0.98874244, 0.19825257, 0.61963299,
       0.44365698, 0.78167436, 0.05262957, 0.32439506, 0.46977262])

In [130]:
b.T

array([[0.4426011 , 0.13941709, 0.98874244, 0.19825257, 0.61963299,
        0.44365698, 0.78167436, 0.05262957, 0.32439506, 0.46977262]])