In [76]:
import numpy as np
import pandas as pd

# Pivoteamento
https://youtu.be/6-iBXVomqb8
<a href="https://githubtocolab.com/cn-ufpe/cn-ufpe.github.io/blob/master/material/10_pivoteamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab"/></a>

## Eliminação gaussiana sem pivoteamento

In [77]:
def eliminacao_gaussiana(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes é uma matriz n x n
    termos_independentes é uma matriz n por 1
    '''
    
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    tamanho = len(A)

    for j in range(0, tamanho-1):
        pivo = A[j, j]

        for k in range(j+1, tamanho):
            m = -A[k, j] / pivo
            A[k] = m * A[j] + A[k] # esta linha está realizando muitas operações desnecessárias
            b[k] = m * b[j] + b[k]
            A[k, j] = 0
    
    
    return A, b

In [78]:
def triangular_superior(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes: matriz triangular superior
    termos_independentes: termos independentes do sistema retangular superior
    
    retorna a solução do sistema
    '''
    tamanho = len(matriz_coeficientes)
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    
    
    x = np.zeros(tamanho)
    x[tamanho-1] = b[tamanho-1] / A[tamanho-1, tamanho-1]

    for k in range(tamanho-2, -1, -1):
        soma = b[k]
        for t in range(k, tamanho):
            soma = soma - A[k, t] * x[t]

        x[k] = soma / A[k, k]
    
    return x

In [79]:
def resolver_sistema(matriz_coeficientes, termos_independentes):
    tA, tb = eliminacao_gaussiana(matriz_coeficientes, termos_independentes)
    x = triangular_superior(tA, tb)
    return x

In [80]:
A = np.random.rand(3, 3)
b = np.random.rand(3, 1)
pd.DataFrame(A)

          0         1         2
0  0.172341  0.137136  0.932595
1  0.696818  0.066000  0.755463
2  0.753876  0.923025  0.711525

In [81]:
x = resolver_sistema(A, b)
pd.DataFrame(x)

          0
0 -0.142970
1  0.024904
2  0.156011

In [82]:
A @ x

array([0.12427096, 0.01988013, 0.02621099])

In [83]:
b.T

array([[0.12427096, 0.01988013, 0.02621099]])

## O que ocorrerá se o pivô for igual a zero?

In [84]:
A[0, 0] = 0
x = resolver_sistema(A, b)
print('x = ', x)
print()

x =  [nan nan nan]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: divide by zero encountered in double_scalars
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in multiply
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in double_scalars

In [85]:
A

array([[0.        , 0.13713575, 0.93259546],
       [0.69681816, 0.06600017, 0.75546305],
       [0.75387619, 0.92302454, 0.71152476]])

Vamos repetir apenas a primeira linha da substituição para frente para identificar o problema.

In [87]:
pivo = A[0, 0]
m = -A[1,0] / A[0, 0] # aqui está ocorrendo uma divisão por 0

print(m)
print()

-inf

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in double_scalars

In [88]:
A[1] = m*A[0] + A[1]

print(A)
print()

[[0.         0.13713575 0.93259546]
 [       nan       -inf       -inf]
 [0.75387619 0.92302454 0.71152476]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in multiply
  """Entry point for launching an IPython kernel.

## O que ocorrá se o pivô for um número próximo a zero?

In [89]:
matriz_coeficientes = np.array([[1e-16, 1.], [1., 1.]])
termos_independentes = np.array([[1.], [2.]])

A = np.copy(matriz_coeficientes)
b = np.copy(termos_independentes)

In [90]:
A

array([[1.e-16, 1.e+00],
       [1.e+00, 1.e+00]])

In [91]:
b.T

array([[1., 2.]])

In [93]:
x = resolver_sistema(A, b)

In [95]:
x

array([2.22044605, 1.        ])

In [96]:
x[1]

0.9999999999999998

In [97]:
A @ x

array([1.        , 3.22044605])

Vamos realizar cada passo da eliminação gaussiana para verificar o problema.

In [98]:
pivo = A[0, 0]
m = -A[1,0] / A[0, 0] # aqui está ocorrendo uma divisão por um número próximo a zero
print(m)

-1e+16

In [99]:
A[1] = A[1] = m*A[0] + A[1]
b[1] = m*b[0] + b[1]

In [100]:
A

array([[ 1.e-16,  1.e+00],
       [ 0.e+00, -1.e+16]])

In [101]:
b

array([[ 1.e+00],
       [-1.e+16]])

Você consegue verificar algum erro no resultado das  operações acima? E qual a justificativa para este erro?

In [102]:
x[1] = b[1] / A[1, 1]
x[0] = (b[0] - A[0, 1] * x[1]) / A[0, 0]
print(x)

[2.22044605 1.        ]

In [103]:
matriz_coeficientes @ x

array([1.        , 3.22044605])

In [104]:
termos_independentes

array([[1.],
       [2.]])

- O algoritmo de eliminação gaussiana não produz a saída correta quando um pivô é igual a zero ou próximo a zero.

- Para evitar este problema vamos realizar o pivoteamento parcial.

In [105]:
(b[0] - A[0, 1] * x[1]) / 10**-16

array([2.22044605])

In [106]:
print(x[1])

0.9999999999999998

In [107]:
print("{:.50f}".format(b[1, 0]))

-9999999999999998.00000000000000000000000000000000000000000000000000

In [108]:
b

array([[ 1.e+00],
       [-1.e+16]])

## Pivoteamento parcial

In [109]:
# Inicialização de uma matriz A 
np.random.seed(1)
A = 2 * (np.random.rand(10, 10) - 0.5)
b = np.random.rand(10, 1)

for k in range(10):
    A[k, k] = 10 ** -16
    
A[1, 1] = -0.082040
A[2, 2] = 4.036186

In [110]:
pd.DataFrame(A)

              0         1         2  ...             7             8             9
0  1.000000e-16  0.440649 -0.999771  ... -3.088785e-01 -2.064651e-01  7.763347e-02
1 -1.616110e-01 -0.082040 -0.591096  ...  1.173797e-01 -7.192261e-01 -6.037970e-01
2  6.014891e-01  0.936523  4.036186  ... -9.218904e-01 -6.603392e-01  7.562850e-01
3 -8.033063e-01 -0.157785  0.915779  ...  6.692513e-01 -9.634234e-01  5.002886e-01
4  9.777222e-01  0.496331 -0.439112  ... -4.127717e-01 -4.244493e-01 -7.399429e-01
5 -9.612661e-01  0.357671 -0.576744  ... -7.065429e-01  1.786111e-01  3.995167e-01
6 -7.953311e-01 -0.171888  0.388800  ...  2.977822e-02  8.891895e-01  1.731101e-01
7  8.068038e-01 -0.725051 -0.721447  ...  1.000000e-16  5.016242e-01  4.519960e-01
8  7.666122e-01  0.247344  0.501885  ...  9.296801e-01  1.000000e-16  2.433914e-01
9 -7.705081e-01  0.898979 -0.100176  ...  1.473590e-01 -9.942593e-01  1.000000e-16

[10 rows x 10 columns]

In [111]:
x = resolver_sistema(A, b)

In [112]:
print(A @ x)
print('')
print(b.T)

[ 0.3266449   0.42319951  2.05953569 -0.97463821  1.91914269 -0.90463609
 -1.08524902  1.4287363   1.92415615  0.15762876]

[[0.3266449  0.5270581  0.8859421  0.35726976 0.90853515 0.62336012
  0.01582124 0.92943723 0.69089692 0.99732285]]

Eliminação gaussiana com pivoteamento.

**1. Utilizando pivoteamento parcial, qual será o primeiro pivô da matriz $A$?**

In [113]:
pd.DataFrame(A)

              0         1         2  ...             7             8             9
0  1.000000e-16  0.440649 -0.999771  ... -3.088785e-01 -2.064651e-01  7.763347e-02
1 -1.616110e-01 -0.082040 -0.591096  ...  1.173797e-01 -7.192261e-01 -6.037970e-01
2  6.014891e-01  0.936523  4.036186  ... -9.218904e-01 -6.603392e-01  7.562850e-01
3 -8.033063e-01 -0.157785  0.915779  ...  6.692513e-01 -9.634234e-01  5.002886e-01
4  9.777222e-01  0.496331 -0.439112  ... -4.127717e-01 -4.244493e-01 -7.399429e-01
5 -9.612661e-01  0.357671 -0.576744  ... -7.065429e-01  1.786111e-01  3.995167e-01
6 -7.953311e-01 -0.171888  0.388800  ...  2.977822e-02  8.891895e-01  1.731101e-01
7  8.068038e-01 -0.725051 -0.721447  ...  1.000000e-16  5.016242e-01  4.519960e-01
8  7.666122e-01  0.247344  0.501885  ...  9.296801e-01  1.000000e-16  2.433914e-01
9 -7.705081e-01  0.898979 -0.100176  ...  1.473590e-01 -9.942593e-01  1.000000e-16

[10 rows x 10 columns]

In [114]:
# np.abs retorna o módulo de um número
# np.argmax retorna o índice do maior elemento

indice_pivo = np.argmax(np.abs(A[:, 0]))
pivo = A[indice_pivo, 0]
print(pivo)
print(indice_pivo)

0.9777221778129894
4

**2. Realize o primeiro passo do pivoteamento parcial**

In [115]:
A[[indice_pivo, 0]] = A[[0, indice_pivo]]

In [116]:
pd.DataFrame(A)

              0         1         2  ...             7             8             9
0  9.777222e-01  0.496331 -0.439112  ... -4.127717e-01 -4.244493e-01 -7.399429e-01
1 -1.616110e-01 -0.082040 -0.591096  ...  1.173797e-01 -7.192261e-01 -6.037970e-01
2  6.014891e-01  0.936523  4.036186  ... -9.218904e-01 -6.603392e-01  7.562850e-01
3 -8.033063e-01 -0.157785  0.915779  ...  6.692513e-01 -9.634234e-01  5.002886e-01
4  1.000000e-16  0.440649 -0.999771  ... -3.088785e-01 -2.064651e-01  7.763347e-02
5 -9.612661e-01  0.357671 -0.576744  ... -7.065429e-01  1.786111e-01  3.995167e-01
6 -7.953311e-01 -0.171888  0.388800  ...  2.977822e-02  8.891895e-01  1.731101e-01
7  8.068038e-01 -0.725051 -0.721447  ...  1.000000e-16  5.016242e-01  4.519960e-01
8  7.666122e-01  0.247344  0.501885  ...  9.296801e-01  1.000000e-16  2.433914e-01
9 -7.705081e-01  0.898979 -0.100176  ...  1.473590e-01 -9.942593e-01  1.000000e-16

[10 rows x 10 columns]

**3. Qual o valor máximo do módulo dos multiplicadores?**

Como o módulo do pivô é o maior na coluna, $\left|\frac{A[k, j]}{pivo[k]}\right| \leq 1$. Onde pivo[k] é o pivô da coluna k após pivoteamento parcial.

**4. Reescreva um laço para zerar os elementos abaixo do pivô da coluna 0**

In [117]:
pivo = A[0, 0]
for k in range(1, 10):
    m = -A[k, 0] / pivo
    A[k] = A[k] + m * A[0]

**5. Qual será o segundo pivô?**

In [118]:
pd.DataFrame(A)

          0             1         2  ...         7         8         9
0  0.977722  4.963313e-01 -0.439112  ... -0.412772 -0.424449 -0.739943
1  0.000000  2.632390e-07 -0.663678  ...  0.049151 -0.789385 -0.726105
2  0.000000  6.311829e-01  4.306325  ... -0.667956 -0.399220  1.211494
3  0.000000  2.500060e-01  0.555000  ...  0.330114 -1.312155 -0.107656
4  0.000000  4.406490e-01 -0.999771  ... -0.308879 -0.206465  0.077633
5  0.000000  8.456486e-01 -1.008465  ... -1.112367 -0.238694 -0.327972
6  0.000000  2.318542e-01  0.031603  ... -0.305992  0.543920 -0.428799
7  0.000000 -1.134617e+00 -0.359098  ...  0.340614  0.851874  1.062587
8  0.000000 -1.418189e-01  0.846184  ...  1.253326  0.332802  0.823566
9  0.000000  1.290120e+00 -0.446224  ... -0.177932 -1.328753 -0.583123

[10 rows x 10 columns]

In [119]:
indice_pivo = np.argmax(np.abs(A[1:, 1])) + 1
# a dimensao de A[1:, 1] é o numero de linhas - 1 e por isso temos que somar 1 ao indice do pivo
pivo = A[indice_pivo, 1]
print(indice_pivo)
print(pivo)

9
1.2901195588840266

**6. Realize o segundo passo do pivoteamento parcial**

In [120]:
A[[indice_pivo, 1]] = A[[1, indice_pivo]]

In [121]:
pd.DataFrame(A)

          0             1         2  ...         7         8         9
0  0.977722  4.963313e-01 -0.439112  ... -0.412772 -0.424449 -0.739943
1  0.000000  1.290120e+00 -0.446224  ... -0.177932 -1.328753 -0.583123
2  0.000000  6.311829e-01  4.306325  ... -0.667956 -0.399220  1.211494
3  0.000000  2.500060e-01  0.555000  ...  0.330114 -1.312155 -0.107656
4  0.000000  4.406490e-01 -0.999771  ... -0.308879 -0.206465  0.077633
5  0.000000  8.456486e-01 -1.008465  ... -1.112367 -0.238694 -0.327972
6  0.000000  2.318542e-01  0.031603  ... -0.305992  0.543920 -0.428799
7  0.000000 -1.134617e+00 -0.359098  ...  0.340614  0.851874  1.062587
8  0.000000 -1.418189e-01  0.846184  ...  1.253326  0.332802  0.823566
9  0.000000  2.632390e-07 -0.663678  ...  0.049151 -0.789385 -0.726105

[10 rows x 10 columns]

**7. Reescreva um laço para zerar os elementos da coluna 1**

In [122]:
pivo = A[1, 1]
for k in range(2, 10):
    m = -A[k, 1] / pivo
    A[k] = A[k] + m * A[1]
    A[k, 1] = 0

In [123]:
pd.DataFrame(A)

          0         1         2  ...         7         8         9
0  0.977722  0.496331 -0.439112  ... -0.412772 -0.424449 -0.739943
1  0.000000  1.290120 -0.446224  ... -0.177932 -1.328753 -0.583123
2  0.000000  0.000000  4.524638  ... -0.580904  0.250864  1.496783
3  0.000000  0.000000  0.641472  ...  0.364595 -1.054663  0.005345
4  0.000000  0.000000 -0.847360  ... -0.248105  0.247379  0.276803
5  0.000000  0.000000 -0.715974  ... -0.995736  0.632278  0.054254
6  0.000000  0.000000  0.111797  ... -0.274015  0.782717 -0.324003
7  0.000000  0.000000 -0.751537  ...  0.184129 -0.316719  0.549751
8  0.000000  0.000000  0.797132  ...  1.233767  0.186736  0.759465
9  0.000000  0.000000 -0.663678  ...  0.049151 -0.789385 -0.726105

[10 rows x 10 columns]

**7. Realize o pivoteamento para a coluna 2 e eeescreva um laço para zerar os elementos abaixo do pivô da coluna 2**

In [124]:
indice_pivo = np.argmax(np.abs(A[2:, 2])) + 2
# a dimensao de A[1:, 1] é o numero de linhas - 1 e por isso temos que somar 1 ao indice do pivo
pivo = A[indice_pivo, 2]
print(indice_pivo)
print(pivo)

A[[indice_pivo, 2]] = A[[2, indice_pivo]]

pivo = A[2, 2]
for k in range(3, 10):
    m = -A[k, 2] / pivo
    A[k] = A[k] + m * A[2]
    A[k, 2] = 0

pd.DataFrame(A)

2
4.524637669380695

          0         1         2  ...         7         8         9
0  0.977722  0.496331 -0.439112  ... -0.412772 -0.424449 -0.739943
1  0.000000  1.290120 -0.446224  ... -0.177932 -1.328753 -0.583123
2  0.000000  0.000000  4.524638  ... -0.580904  0.250864  1.496783
3  0.000000  0.000000  0.000000  ...  0.446951 -1.090228 -0.206859
4  0.000000  0.000000  0.000000  ... -0.356895  0.294360  0.557116
5  0.000000  0.000000  0.000000  ... -1.087658  0.671974  0.291103
6  0.000000  0.000000  0.000000  ... -0.259662  0.776519 -0.360986
7  0.000000  0.000000  0.000000  ...  0.087642 -0.275051  0.798364
8  0.000000  0.000000  0.000000  ...  1.336108  0.142540  0.495768
9  0.000000  0.000000  0.000000  ... -0.036056 -0.752588 -0.506555

[10 rows x 10 columns]

**8. Realize o pivoteamento para a coluna 3 e eeescreva um laço para zerar os elementos abaixo do pivô da coluna 3**

In [125]:
indice_pivo = np.argmax(np.abs(A[3:, 3])) + 3 
# a dimensao de A[1:, 1] é o numero de linhas - 1 e por isso temos que somar 1 ao indice do pivo
pivo = A[indice_pivo, 3]
print(indice_pivo)
print(pivo)

A[[indice_pivo, 3]] = A[[3, indice_pivo]]

pivo = A[3, 3]
for k in range(4, 10):
    m = -A[k, 3] / pivo
    A[k] = A[k] + m * A[3]
    A[k, 3] = 0

pd.DataFrame(A)

9
0.8121087176429337

          0         1         2  ...         7         8         9
0  0.977722  0.496331 -0.439112  ... -0.412772 -0.424449 -0.739943
1  0.000000  1.290120 -0.446224  ... -0.177932 -1.328753 -0.583123
2  0.000000  0.000000  4.524638  ... -0.580904  0.250864  1.496783
3  0.000000  0.000000  0.000000  ... -0.036056 -0.752588 -0.506555
4  0.000000  0.000000  0.000000  ... -0.385992 -0.312981  0.148324
5  0.000000  0.000000  0.000000  ... -1.102958  0.352627  0.076156
6  0.000000  0.000000  0.000000  ... -0.250979  0.957756 -0.238998
7  0.000000  0.000000  0.000000  ...  0.115666  0.309896  1.192083
8  0.000000  0.000000  0.000000  ...  1.307660 -0.451232  0.096109
9  0.000000  0.000000  0.000000  ...  0.464490 -0.724141  0.039549

[10 rows x 10 columns]

**9. Realize o pivoteamento para a coluna j e eeescreva um laço para zerar os elementos abaixo do pivô da coluna j**

In [126]:
j = 4

indice_pivo = np.argmax(np.abs(A[j:, j])) + j
# a dimensao de A[1:, 1] é o numero de linhas - 1 e por isso temos que somar 1 ao indice do pivo
pivo = A[indice_pivo, j]
print(indice_pivo)
print(pivo)

A[[indice_pivo, j]] = A[[j, indice_pivo]]

pivo = A[j, j]
for k in range(j+1, 10):
    m = -A[k, j] / pivo
    A[k] = A[k] + m * A[j]
    A[k, j] = 0

pd.DataFrame(A)

8
-1.2770359702081862

          0         1         2  ...         7         8         9
0  0.977722  0.496331 -0.439112  ... -0.412772 -0.424449 -0.739943
1  0.000000  1.290120 -0.446224  ... -0.177932 -1.328753 -0.583123
2  0.000000  0.000000  4.524638  ... -0.580904  0.250864  1.496783
3  0.000000  0.000000  0.000000  ... -0.036056 -0.752588 -0.506555
4  0.000000  0.000000  0.000000  ...  1.307660 -0.451232  0.096109
5  0.000000  0.000000  0.000000  ... -1.217359  0.392104  0.067747
6  0.000000  0.000000  0.000000  ... -0.957560  1.201574 -0.290930
7  0.000000  0.000000  0.000000  ...  0.537896  0.164198  1.223116
8  0.000000  0.000000  0.000000  ... -1.562521  0.093001  0.061852
9  0.000000  0.000000  0.000000  ...  1.180825 -0.971325  0.092198

[10 rows x 10 columns]

**10. Escreva uma função `pivoteamento(A, j)` que realiza o pivoteamento parcial para a coluna `j` da matriz `A`.**

In [127]:
def pivoteamento(A, b, j):
    indice_pivo = np.argmax(np.abs(A[j:, j])) + j
    A[[indice_pivo, j]] = A[[j, indice_pivo]]
    b[[indice_pivo, j]] = b[[j, indice_pivo]]

In [128]:
def eliminacao_gaussiana(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes é uma matriz n x n
    termos_independentes é uma matriz n por 1
    '''
    
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    tamanho = len(A)

    for j in range(0, tamanho-1):
        pivoteamento(A, b, j) ##!!!!!!!!! adicionar esta linha #############

        pivo = A[j, j]

        for k in range(j+1, tamanho):
            m = -A[k, j] / pivo
            A[k] = m * A[j] + A[k] # esta linha está realizando muitas operações desnecessárias
            b[k] = m * b[j] + b[k]
            A[k, j] = 0
    
    
    return A, b

**Verificar a solução do sistema**

In [130]:
# Inicialização de uma matriz A 
np.random.seed(1)
A = 2 * (np.random.rand(10, 10) - 0.5)
b = np.random.rand(10, 1)

for k in range(10):
    A[k, k] = 10 ** -16
    
A[1, 1] = -0.082040
A[2, 2] = 4.036186

x = resolver_sistema(A, b)
print(A @ x)
print()
print(b.T)

[0.3266449  0.5270581  0.8859421  0.35726976 0.90853515 0.62336012
 0.01582124 0.92943723 0.69089692 0.99732285]

[[0.3266449  0.5270581  0.8859421  0.35726976 0.90853515 0.62336012
  0.01582124 0.92943723 0.69089692 0.99732285]]

O numpy possui para resolução de matrizes que utiliza a eliminação gaussiana. Devemos utilizar a função do numpy ou nossa implementação?

In [131]:
A = np.random.rand(1000, 1000)
b = np.random.rand(1000, 1)
%timeit resolver_sistema(A, b)

1 loop, best of 5: 5.32 s per loop

In [132]:
%timeit np.linalg.solve(A, b)

10 loops, best of 5: 37.6 ms per loop